language: node_js
node_js:
- "6"
services:
  - docker
sudo: true
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y make python gcc g++
install:
- npm install -g bower gulp
- npm install
- bower install
script:
- gulp build
- docker build -t ccr.ccs.tencentyun.com/zino/app-share ./docker
deploy:
  provider: script
  skip_cleanup: true
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin ccr.ccs.tencentyun.com && docker push ccr.ccs.tencentyun.com/zino/app-share
  on:
    branch: master
dist: trusty
