language: node_js
node_js:
- "6"
sudo: true
addons:
  ssh_known_hosts: api.zino.co
branches:
  only:
  - master
cache:
  directories:
  - node_modules
  - bower_components
before_install:
- openssl aes-256-cbc -K $encrypted_350b285dc70d_key -iv $encrypted_350b285dc70d_iv -in deploy_rsa.enc -out deploy_rsa -d
- sudo apt-get -qq update
- sudo apt-get install -y make python gcc g++
install:
- npm install -g bower gulp
- npm install
- bower install
script:
- gulp build
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -re "ssh -p $ALI_PORT" --delete-after --exclude="vendor" $TRAVIS_BUILD_DIR/dist/
    $ALI_URI:/usr/share/nginx/app-share
  on:
    branch: master
dist: trusty
